### PR TITLE
fix(SCT-263): fix not auditing personal relationship details

### PR DESCRIPTION
**Pull request by chubberlisk**
## Link to JIRA ticket

https://hackney.atlassian.net/browse/SCT-263

### *What is the problem we're trying to solve*

We are missing the `IAuditEntity` for `PersonalRelationshipDetail` which means that we're not auditing it (we had the columns but missed the inheritance).

### *What changes have we introduced*

This PR adds `IAuditEntity` for `PersonalRelationshipDetail` and adds tests to cover this.

#### _Checklist_

- [ ] Added end-to-end (i.e. integration) tests where necessary e.g to test complete functionality of a newly added feature
- [x] Added tests to cover all new production code
- [x] Added comments to the README or updated relevant documentation _(add link to documentation)_, where necessary.
- [x] Checked all code for possible refactoring
- [x] Code pipeline builds correctly

### CODE REVIEW

**Review by mapleleafjack — APPROVED** [review]

**Comment by LBHTKarki** [comment]
@chubberlisk just to confirm that when dealing with audit entities, the `CreatedAt` and `LastModifiedAt` fields will be populated automatically on save. However the `CreatedBy` and `LastModifiedBy` fields should be populated in the code using worker's email. We can't grab that automatically at the moment due to lack of user context.

**Comment by chubberlisk** [comment]
> @chubberlisk just to confirm that when dealing with audit entities, the `CreatedAt` and `LastModifiedAt` fields will be populated automatically on save. However the `CreatedBy` and `LastModifiedBy` fields should be populated in the code using worker's email. We can't grab that automatically at the moment due to lack of user context.

Ahhhh, are you saying that we need to update the frontend to send the worker's email as part of the request for adding a relationship and then update the API to handle the worker's email and save it as `CreatedBy`?

**Comment by LBHTKarki** [comment]
> > @chubberlisk just to confirm that when dealing with audit entities, the `CreatedAt` and `LastModifiedAt` fields will be populated automatically on save. However the `CreatedBy` and `LastModifiedBy` fields should be populated in the code using worker's email. We can't grab that automatically at the moment due to lack of user context.
> 
> Ahhhh @LBHTKarki, are you saying that we need to update the frontend to send the worker's email as part of the request for adding a relationship and then update the API to handle the worker's email and save it as `CreatedBy`?

@chubberlisk yes, exactly. I completely forgot that aspect of the object when we discussed it. That property is required for adding and modifying records

**Comment by chubberlisk** [comment]
> > > @chubberlisk just to confirm that when dealing with audit entities, the `CreatedAt` and `LastModifiedAt` fields will be populated automatically on save. However the `CreatedBy` and `LastModifiedBy` fields should be populated in the code using worker's email. We can't grab that automatically at the moment due to lack of user context.
> > 
> > 
> > Ahhhh @LBHTKarki, are you saying that we need to update the frontend to send the worker's email as part of the request for adding a relationship and then update the API to handle the worker's email and save it as `CreatedBy`?
> 
> @chubberlisk yes, exactly. I completely forgot that aspect of the object when we discussed it. That property is required for adding and modifying records

Okay, got it! Will update the frontend to send this and then update this PR to make sure we're saving this.

**Comment by chubberlisk** [comment]
Closing this PR because of the Git weirdness and will create a new PR to handle the `CreatedBy` added to the request once the frontend is updated.

**Pull request closed without merging**
