### PR TITLE
Add default value for marked for deletion flag

### PR DESCRIPTION
**Pull request by LBHTKarki**
### *What is the problem we're trying to solve*

Marked for deletion flag doesn't have default value which means all records get filtered out by APIs.

### *What changes have we introduced*

Set default value to false so the API returns correct records.

#### _Checklist_
- [x] Code pipeline builds correctly

### *Follow up actions after merging PR*

Run the alter table scripts in the PR

### CODE REVIEW

**Review by chubberlisk — COMMENTED** [review]
Will setting it default mean all current values will be `false`? By that I mean do we have to set as default and then run an update statement to set current ones to `false`?

**Comment by LBHTKarki** [comment]
> Will setting it default mean all current values will be `false`? By that I mean do we have to set as default and then run an update statement to set current ones to `false`?

@chubberlisk You are correct, update statements are also required. I have pushed an update to add those.

**Comment by LBHTKarki** [comment]
@chubberlisk I've pushed the manual update plan to this same PR for simplicity

**Review by chubberlisk — APPROVED** [review]
👍

**Pull request merged**
